### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by rzdong** [jaywcjlove/rehype-ignore#2]
Uncaught SyntaxError: Unexpected token .

userAgent  Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Mobile Safari/537.36

other issue ： https://github.com/jaywcjlove/rehype-attr/issues/45

<img width="942" alt="image" src="https://user-images.githubusercontent.com/19262880/211487149-c0fd644c-5f9c-424f-b82d-a6b962576ae8.png">

**Comment by vinod77** [comment]
+1

**Comment by rzdong** [comment]
> +1
useful
{
            test: /\.m?js$/,
            include: [
              path.resolve("./node_modules/rehype-ignore/lib/index.js")
            ],
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env']
              }
            }
          }

**Comment by jaywcjlove** [comment]
@rzdong @vinod77 Upgrade `v1.0.4`
